projectName: Taxi-Agency
gitUrl: https://github.com/Karunika/Taxi_Agency_OODB
version: 0.0.0
description: Object Oriented Database model for a Taxi Agency
scripts:
  build: make
  reste: make reset
  clean: clean
private: false
keywords:
  taxi
  agency
  database
  object
  cpp
  model
author: Karunika
license: MIT
